import { Status } from "@prisma/client";

export const countries = [
  {
      id: "country-1",
      nameEn: "United Arab Emirates", 
      nameAr: "الإمارات العربية المتحدة",
      code: "UAE",
      flag: "🇦🇪",
      currency: "AED",
      dialCode: "+971",
      isActive: true
  },
  {
      id: "country-2",
      nameEn: "Saudi Arabia",
      nameAr: "المملكة العربية السعودية", 
      code: "SAU",
      flag: "🇸🇦",
      currency: "SAR",
      dialCode: "+966",
      isActive: true
  },
  {
      id: "country-3",
      nameEn: "Syria",
      nameAr: "سوريا",
      code: "SYR", 
      flag: "🇸🇾",
      currency: "SYP",
      dialCode: "+963",
      isActive: true
  },
  {
      id: "country-4",
      nameEn: "Egypt",
      nameAr: "مصر",
      code: "EGY",
      flag: "🇪🇬",
      currency: "EGP", 
      dialCode: "+20",
      isActive: true
  },
  {
      id: "country-5",
      nameEn: "Qatar",
      nameAr: "قطر",
      code: "QAT",
      flag: "🇶🇦",
      currency: "QAR",
      dialCode: "+974",
      isActive: true
  },
  {
      id: "country-6",
      nameEn: "Kuwait",
      nameAr: "الكويت",
      code: "KWT",
      flag: "🇰🇼",
      currency: "KWD",
      dialCode: "+965",
      isActive: true
  }
];

export const cities = [
  {
      id: "city-1",
      nameEn: "Dubai",
      nameAr: "دبي",
      countryId: "country-1",
      latitude: 25.2048,
      longitude: 55.2708,
      isActive: true
  },
  {
      id: "city-2",
      nameEn: "Abu Dhabi",
      nameAr: "أبوظبي",
      countryId: "country-1",
      latitude: 24.4539,
      longitude: 54.3773,
      isActive: true
  },
  {
      id: "city-3",
      nameEn: "Riyadh",
      nameAr: "الرياض",
      countryId: "country-2",
      latitude: 24.7136,
      longitude: 46.6753,
      isActive: true
  }
];

export const categories = [
  // Транспорт
  {
      id: "cat-1",
      nameEn: "Vehicles",
      nameAr: "مركبات",
      slug: "vehicles", 
      icon: "🚗",
      isActive: true,
      order: 1
  },
  {
      id: "cat-1-1",
      nameEn: "Cars",
      nameAr: "سيارات",
      slug: "cars",
      icon: "🚘",
      parentId: "cat-1",
      isActive: true,
      order: 1
  },
  {
      id: "cat-1-2", 
      nameEn: "Motorcycles",
      nameAr: "دراجات نارية",
      slug: "motorcycles",
      icon: "🏍️",
      parentId: "cat-1",
      isActive: true,
      order: 2
  },
  {
      id: "cat-1-3",
      nameEn: "Spare Parts",
      nameAr: "قطع غيار",
      slug: "spare-parts",
      icon: "🔧",
      parentId: "cat-1", 
      isActive: true,
      order: 3
  },

  // Недвижимость
  {
      id: "cat-2",
      nameEn: "Real Estate",
      nameAr: "عقارات",
      slug: "real-estate",
      icon: "🏠",
      isActive: true,
      order: 2
  },
  {
      id: "cat-2-1",
      nameEn: "Apartments",
      nameAr: "شقق",
      slug: "apartments",
      icon: "🏢",
      parentId: "cat-2",
      isActive: true,
      order: 1
  },
  {
      id: "cat-2-2",
      nameEn: "Villas",
      nameAr: "فلل",
      slug: "villas",
      icon: "🏡",
      parentId: "cat-2",
      isActive: true,
      order: 2
  },
  {
      id: "cat-2-3",
      nameEn: "Commercial",
      nameAr: "تجاري",
      slug: "commercial",
      icon: "🏪",
      parentId: "cat-2",
      isActive: true,
      order: 3
  },

  // Электроника
  {
      id: "cat-3",
      nameEn: "Electronics",
      nameAr: "إلكترونيات",
      slug: "electronics",
      icon: "📱",
      isActive: true,
      order: 3
  },
  {
      id: "cat-3-1",
      nameEn: "Phones",
      nameAr: "هواتف",
      slug: "phones",
      icon: "📱",
      parentId: "cat-3",
      isActive: true,
      order: 1
  },
  {
      id: "cat-3-2",
      nameEn: "Laptops",
      nameAr: "حواسيب محمولة",
      slug: "laptops",
      icon: "💻",
      parentId: "cat-3",
      isActive: true,
      order: 2
  },
  {
      id: "cat-3-3",
      nameEn: "Gaming",
      nameAr: "ألعاب",
      slug: "gaming",
      icon: "🎮",
      parentId: "cat-3",
      isActive: true,
      order: 3
  },

  // Мода
  {
      id: "cat-4",
      nameEn: "Fashion",
      nameAr: "أزياء",
      slug: "fashion",
      icon: "👕",
      isActive: true,
      order: 4
  },
  {
      id: "cat-4-1",
      nameEn: "Men's Clothing",
      nameAr: "ملابس رجالية",
      slug: "mens-clothing",
      icon: "👔",
      parentId: "cat-4",
      isActive: true,
      order: 1
  },
  {
      id: "cat-4-2",
      nameEn: "Women's Clothing",
      nameAr: "ملابس نسائية",
      slug: "womens-clothing",
      icon: "👗",
      parentId: "cat-4",
      isActive: true,
      order: 2
  },
  {
      id: "cat-4-3",
      nameEn: "Accessories",
      nameAr: "اكسسوارات",
      slug: "accessories",
      icon: "👜",
      parentId: "cat-4",
      isActive: true,
      order: 3
  },

  // Мебель и интерьер
  {
      id: "cat-5",
      nameEn: "Furniture & Interior",
      nameAr: "أثاث وديكور",
      slug: "furniture-interior",
      icon: "🛋️",
      isActive: true,
      order: 5
  },
  {
      id: "cat-5-1",
      nameEn: "Living Room",
      nameAr: "غرفة المعيشة",
      slug: "living-room",
      icon: "🛋️",
      parentId: "cat-5",
      isActive: true,
      order: 1
  },
  {
      id: "cat-5-2",
      nameEn: "Bedroom",
      nameAr: "غرفة النوم",
      slug: "bedroom",
      icon: "🛏️",
      parentId: "cat-5",
      isActive: true,
      order: 2
  },
  {
      id: "cat-5-3",
      nameEn: "Kitchen",
      nameAr: "مطبخ",
      slug: "kitchen",
      icon: "🍳",
      parentId: "cat-5",
      isActive: true,
      order: 3
  },

  // Спорт и отдых
  {
      id: "cat-6",
      nameEn: "Sports & Leisure",
      nameAr: "رياضة وترفيه",
      slug: "sports-leisure",
      icon: "⚽",
      isActive: true,
      order: 6
  },
  {
      id: "cat-6-1",
      nameEn: "Fitness Equipment",
      nameAr: "معدات رياضية",
      slug: "fitness",
      icon: "🏋️",
      parentId: "cat-6",
      isActive: true,
      order: 1
  },
  {
      id: "cat-6-2",
      nameEn: "Outdoor Sports",
      nameAr: "رياضات خارجية",
      slug: "outdoor-sports",
      icon: "🎣",
      parentId: "cat-6",
      isActive: true,
      order: 2
  },
  {
      id: "cat-6-3",
      nameEn: "Water Sports",
      nameAr: "رياضات مائية",
      slug: "water-sports",
      icon: "🏊",
      parentId: "cat-6",
      isActive: true,
      order: 3
  },

  // Бытовая техника
  {
      id: "cat-7",
      nameEn: "Home Appliances",
      nameAr: "أجهزة منزلية",
      slug: "home-appliances",
      icon: "🔌",
      isActive: true,
      order: 7
  },
  {
      id: "cat-7-1",
      nameEn: "Kitchen Appliances",
      nameAr: "أجهزة المطبخ",
      slug: "kitchen-appliances",
      icon: "🍳",
      parentId: "cat-7",
      isActive: true,
      order: 1
  },
  {
      id: "cat-7-2",
      nameEn: "Cleaning Equipment",
      nameAr: "معدات تنظيف",
      slug: "cleaning",
      icon: "🧹",
      parentId: "cat-7",
      isActive: true,
      order: 2
  },
  {
      id: "cat-7-3",
      nameEn: "Climate Control",
      nameAr: "تحكم بالمناخ",
      slug: "climate",
      icon: "❄️",
      parentId: "cat-7",
      isActive: true,
      order: 3
  },

  // Животные
  {
      id: "cat-8",
      nameEn: "Pets",
      nameAr: "حيوانات أليفة",
      slug: "pets",
      icon: "🐾",
      isActive: true,
      order: 8
  },
  {
      id: "cat-8-1",
      nameEn: "Dogs",
      nameAr: "كلاب",
      slug: "dogs",
      icon: "🐕",
      parentId: "cat-8",
      isActive: true,
      order: 1
  },
  {
      id: "cat-8-2",
      nameEn: "Cats",
      nameAr: "قطط",
      slug: "cats",
      icon: "🐈",
      parentId: "cat-8",
      isActive: true,
      order: 2
  },
  {
      id: "cat-8-3",
      nameEn: "Pet Supplies",
      nameAr: "مستلزمات الحيوانات",
      slug: "pet-supplies",
      icon: "🦴",
      parentId: "cat-8",
      isActive: true,
      order: 3
  },

  // Услуги
  {
      id: "cat-9",
      nameEn: "Services",
      nameAr: "خدمات",
      slug: "services",
      icon: "🛠️",
      isActive: true,
      order: 9
  },
  {
      id: "cat-9-1",
      nameEn: "Home Services",
      nameAr: "خدمات منزلية",
      slug: "home-services",
      icon: "🏠",
      parentId: "cat-9",
      isActive: true,
      order: 1
  },
  {
      id: "cat-9-2",
      nameEn: "Business Services",
      nameAr: "خدمات تجارية",
      slug: "business-services",
      icon: "💼",
      parentId: "cat-9",
      isActive: true,
      order: 2
  },
  {
      id: "cat-9-3",
      nameEn: "Education",
      nameAr: "تعليم",
      slug: "education",
      icon: "📚",
      parentId: "cat-9",
      isActive: true,
      order: 3
  },

  // Хобби и развлечения
  {
      id: "cat-10",
      nameEn: "Hobbies & Entertainment",
      nameAr: "هوايات وترفيه",
      slug: "hobbies",
      icon: "🎨",
      isActive: true,
      order: 10
  },
  {
      id: "cat-10-1",
      nameEn: "Musical Instruments",
      nameAr: "آلات موسيقية",
      slug: "music",
      icon: "🎸",
      parentId: "cat-10",
      isActive: true,
      order: 1
  },
  {
      id: "cat-10-2",
      nameEn: "Art & Crafts",
      nameAr: "فنون وحرف",
      slug: "art",
      icon: "🎨",
      parentId: "cat-10",
      isActive: true,
      order: 2
  },
  {
      id: "cat-10-3",
      nameEn: "Books & Magazines",
      nameAr: "كتب ومجلات",
      slug: "books",
      icon: "📚",
      parentId: "cat-10",
      isActive: true,
      order: 3
  }
];

export const adts = [
  {
      title: "2023 Toyota Camry",
      description: "Excellent condition, low mileage",
      price: '75000.00',
      status: Status.PUBLISHED,
      countryId: "country-1", 
      cityId: "city-1",
      address: "Dubai Marina",
      latitude: 25.2048,
      longitude: 55.2708,
      userId: 1,
      categoryId: "cat-1-1",
      views: 0,
      image: "https://example.com/camry.jpg",
      contactPhone: "+971501234567",
      isPromoted: true
  },
  {
      title: "iPhone 14 Pro Max",
      description: "Brand new sealed iPhone 14 Pro Max 256GB",
      price: '4499.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1", 
      address: "Mall of Emirates",
      latitude: 25.1181,
      longitude: 55.2008,
      userId: 1,
      categoryId: "cat-3-1",
      views: 0,
      image: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb",
      contactPhone: "+971501234567",
      isPromoted: false
  },
  {
      title: "Luxury Villa with Pool",
      description: "6 bedrooms, 7 bathrooms, private pool, garden",
      price: '12000000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Palm Jumeirah",
      latitude: 25.1124,
      longitude: 55.1390,
      userId: 1,
      categoryId: "cat-2-2",
      views: 0,
      image: "https://images.unsplash.com/photo-1613977257363-707ba9348227",
      contactPhone: "+971501234567",
      isPromoted: true
  },
  {
      title: "Designer Gucci Bag",
      description: "Original Gucci bag from new collection",
      price: '8500.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Dubai Mall",
      latitude: 25.1972,
      longitude: 55.2744,
      userId: 1,
      categoryId: "cat-4-3",
      views: 0,
      image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa",
      contactPhone: "+971501234567",
      isPromoted: false
  },
  {
      title: "2022 Mercedes-Benz S-Class",
      description: "Luxury sedan with full options, only 3000km",
      price: '450000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Sheikh Zayed Road",
      latitude: 25.2048,
      longitude: 55.2708,
      userId: 1,
      categoryId: "cat-1-1",
      views: 0,
      image: "https://images.unsplash.com/photo-1622194993799-e7f132e4126a",
      contactPhone: "+971501234567",
      isPromoted: true
  },
  {
      title: "Gaming PC Setup",
      description: "High-end gaming PC with RTX 4090",
      price: '12000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Business Bay",
      latitude: 25.1872,
      longitude: 55.2744,
      userId: 1,
      categoryId: "cat-3-3",
      views: 0,
      image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c",
      contactPhone: "+971501234567",
      isPromoted: false
  },
  {
      title: "Luxury Apartment in Downtown",
      description: "3BR apartment with Burj Khalifa view",
      price: '3500000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Downtown Dubai",
      latitude: 25.2048,
      longitude: 55.2708,
      userId: 1,
      categoryId: "cat-2-1",
      views: 0,
      image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
      contactPhone: "+971501234567",
      isPromoted: true
  },
  {
      title: "Professional DJ Equipment",
      description: "Complete DJ setup with Pioneer CDJs and mixer",
      price: '15000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "JLT",
      latitude: 25.0750,
      longitude: 55.1375,
      userId: 1,
      categoryId: "cat-10-1",
      views: 0,
      image: "https://images.unsplash.com/photo-1571935441005-55aaae1bd080",
      contactPhone: "+971501234567",
      isPromoted: false
  },
  {
      title: "Modern Living Room Set",
      description: "Complete furniture set with sofa and tables",
      price: '25000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Dubai Marina",
      latitude: 25.2048,
      longitude: 55.2708,
      userId: 1,
      categoryId: "cat-5-1",
      views: 0,
      image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
      contactPhone: "+971501234567",
      isPromoted: true
  },
  {
      title: "MacBook Pro 16-inch",
      description: "M2 Max chip, 32GB RAM, 1TB SSD",
      price: '9500.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Dubai Mall",
      latitude: 25.1972,
      longitude: 55.2744,
      userId: 1,
      categoryId: "cat-3-2",
      views: 0,
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
      contactPhone: "+971501234567",
      isPromoted: false
  },
  {
      title: "iPhone 14 Pro Max",
      description: "Brand new, 256GB storage, Space Black",
      price: '4500.00',
      status: Status.PUBLISHED,
      countryId: "country-1", 
      cityId: "city-1",
      address: "Mall of Emirates",
      latitude: 25.1181,
      longitude: 55.2008,
      userId: 1,
      categoryId: "cat-3-1",
      views: 0,
      image: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb",
      contactPhone: "+971501234567",
      isPromoted: true
  },
  {
      title: "Designer Handbag",
      description: "Authentic Louis Vuitton Neverfull MM",
      price: '6000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1", 
      address: "Dubai Mall",
      latitude: 25.1972,
      longitude: 55.2744,
      userId: 1,
      categoryId: "cat-4-3",
      views: 0,
      image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
      contactPhone: "+971501234567",
      isPromoted: false
  },
  {
      title: "Modern Kitchen Set",
      description: "Complete kitchen cabinets with appliances",
      price: '35000.00',
      status: Status.PUBLISHED,
      countryId: "country-1",
      cityId: "city-1",
      address: "Business Bay",
      latitude: 25.1857,
      longitude: 55.2644,
      userId: 1,
      categoryId: "cat-5-3",
      views: 0,
      image: "https://images.unsplash.com/photo-1556911220-bff31c812dba",
      contactPhone: "+971501234567",
      isPromoted: true
  },
  {
    title: "2023 Toyota Camry",
    description: "Excellent condition, low mileage",
    price: '75000.00',
    status: Status.PUBLISHED,
    countryId: "country-1", 
    cityId: "city-1",
    address: "Dubai Marina",
    latitude: 25.2048,
    longitude: 55.2708,
    userId: 1,
    categoryId: "cat-1-1",
    views: 0,
    image: "https://example.com/camry.jpg",
    contactPhone: "+971501234567",
    isPromoted: true
},
{
    title: "iPhone 14 Pro Max",
    description: "Brand new sealed iPhone 14 Pro Max 256GB",
    price: '4499.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1", 
    address: "Mall of Emirates",
    latitude: 25.1181,
    longitude: 55.2008,
    userId: 1,
    categoryId: "cat-3-1",
    views: 0,
    image: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb",
    contactPhone: "+971501234567",
    isPromoted: false
},
{
    title: "Luxury Villa with Pool",
    description: "6 bedrooms, 7 bathrooms, private pool, garden",
    price: '12000000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Palm Jumeirah",
    latitude: 25.1124,
    longitude: 55.1390,
    userId: 1,
    categoryId: "cat-2-2",
    views: 0,
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227",
    contactPhone: "+971501234567",
    isPromoted: true
},
{
    title: "Designer Gucci Bag",
    description: "Original Gucci bag from new collection",
    price: '8500.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Dubai Mall",
    latitude: 25.1972,
    longitude: 55.2744,
    userId: 1,
    categoryId: "cat-4-3",
    views: 0,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa",
    contactPhone: "+971501234567",
    isPromoted: false
},
{
    title: "2022 Mercedes-Benz S-Class",
    description: "Luxury sedan with full options, only 3000km",
    price: '450000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Sheikh Zayed Road",
    latitude: 25.2048,
    longitude: 55.2708,
    userId: 1,
    categoryId: "cat-1-1",
    views: 0,
    image: "https://images.unsplash.com/photo-1622194993799-e7f132e4126a",
    contactPhone: "+971501234567",
    isPromoted: true
},
{
    title: "Gaming PC Setup",
    description: "High-end gaming PC with RTX 4090",
    price: '12000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Business Bay",
    latitude: 25.1872,
    longitude: 55.2744,
    userId: 1,
    categoryId: "cat-3-3",
    views: 0,
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c",
    contactPhone: "+971501234567",
    isPromoted: false
},
{
    title: "Luxury Apartment in Downtown",
    description: "3BR apartment with Burj Khalifa view",
    price: '3500000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Downtown Dubai",
    latitude: 25.2048,
    longitude: 55.2708,
    userId: 1,
    categoryId: "cat-2-1",
    views: 0,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    contactPhone: "+971501234567",
    isPromoted: true
},
{
    title: "Professional DJ Equipment",
    description: "Complete DJ setup with Pioneer CDJs and mixer",
    price: '15000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "JLT",
    latitude: 25.0750,
    longitude: 55.1375,
    userId: 1,
    categoryId: "cat-10-1",
    views: 0,
    image: "https://images.unsplash.com/photo-1571935441005-55aaae1bd080",
    contactPhone: "+971501234567",
    isPromoted: false
},
{
    title: "Modern Living Room Set",
    description: "Complete furniture set with sofa and tables",
    price: '25000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Dubai Marina",
    latitude: 25.2048,
    longitude: 55.2708,
    userId: 1,
    categoryId: "cat-5-1",
    views: 0,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
    contactPhone: "+971501234567",
    isPromoted: true
},
{
    title: "MacBook Pro 16-inch",
    description: "M2 Max chip, 32GB RAM, 1TB SSD",
    price: '9500.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Dubai Mall",
    latitude: 25.1972,
    longitude: 55.2744,
    userId: 1,
    categoryId: "cat-3-2",
    views: 0,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    contactPhone: "+971501234567",
    isPromoted: false
},
{
    title: "iPhone 14 Pro Max",
    description: "Brand new, 256GB storage, Space Black",
    price: '4500.00',
    status: Status.PUBLISHED,
    countryId: "country-1", 
    cityId: "city-1",
    address: "Mall of Emirates",
    latitude: 25.1181,
    longitude: 55.2008,
    userId: 1,
    categoryId: "cat-3-1",
    views: 0,
    image: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb",
    contactPhone: "+971501234567",
    isPromoted: true
},
{
    title: "Designer Handbag",
    description: "Authentic Louis Vuitton Neverfull MM",
    price: '6000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1", 
    address: "Dubai Mall",
    latitude: 25.1972,
    longitude: 55.2744,
    userId: 1,
    categoryId: "cat-4-3",
    views: 0,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
    contactPhone: "+971501234567",
    isPromoted: false
},
{
    title: "Modern Kitchen Set",
    description: "Complete kitchen cabinets with appliances",
    price: '35000.00',
    status: Status.PUBLISHED,
    countryId: "country-1",
    cityId: "city-1",
    address: "Business Bay",
    latitude: 25.1857,
    longitude: 55.2644,
    userId: 1,
    categoryId: "cat-5-3",
    views: 0,
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba",
    contactPhone: "+971501234567",
    isPromoted: true
}
];

